set -e -x
# export HF_HUB_OFFLINE=1
# MODEL_PATH=/mnt/dolphinfs/hdd_pool/docker/share/jjw/visual_tool/Models/Qwen2.5-VL-3B-Instruct
# MODEL_PATH=/mnt/dolphinfs/hdd_pool/docker/share/jjw/huggingface.co/Qwen/Qwen2.5-0.5B
MODEL_PATH=/mnt/dolphinfs/hdd_pool/docker/share/jjw/visual_tool/Models/Qwen2.5-VL-7B-Instruct
export LD_LIBRARY_PATH=/mnt/dolphinfs/hdd_pool/docker/share/jjw/miniconda3/lib:$LD_LIBRARY_PATH 
export REWARD_MODEL_PATH=/your/path/to/Qwen/QwQ-32B
export HYDRA_FULL_ERROR=1
export RAY_DEDUP_LOGS=0
export WANDB_API_KEY="76ecf2334073036f76da7b9e4eb5bbe934767728"
# export CUDA_VSIBLE_DEVICES=7
DATA=/mnt/dolphinfs/hdd_pool/docker/share/jjw/visual_tool/Data/geo3kv11
# export CUDA_VISIBLE_DEVICES=7
python3 -m verl.trainer.main_ppo\
    algorithm.adv_estimator=grpo\
    data.train_files=$DATA/train.parquet\
    data.val_files=$DATA/test.parquet\
    data.train_batch_size=16\
    data.val_batch_size=1\
    data.max_prompt_length=2048\
    data.max_response_length=4096\
    actor_rollout_ref.model.path=$MODEL_PATH\
    actor_rollout_ref.model.use_remove_padding=True\
    actor_rollout_ref.model.enable_gradient_checkpointing=True\
    actor_rollout_ref.actor.optim.lr=1e-6\
    actor_rollout_ref.actor.ppo_mini_batch_size=8\
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=2\
    actor_rollout_ref.actor.use_kl_loss=True\
    actor_rollout_ref.actor.kl_loss_coef=0.001\
    actor_rollout_ref.actor.kl_loss_type=low_var_kl\
    actor_rollout_ref.actor.fsdp_config.param_offload=False\
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False\
    actor_rollout_ref.actor.state_masking=True\
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=2\
    actor_rollout_ref.rollout.tensor_model_parallel_size=2\
    actor_rollout_ref.rollout.max_num_batched_tokens=8192\
    actor_rollout_ref.rollout.name=vllm\
    actor_rollout_ref.rollout.gpu_memory_utilization=0.7\
    actor_rollout_ref.rollout.n=2\
    actor_rollout_ref.rollout.max_turns=2\
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=2\
    actor_rollout_ref.ref.fsdp_config.param_offload=False\
    actor_rollout_ref.rollout.multi_turn.enable=True\
    actor_rollout_ref.env.name=search_vl\
    actor_rollout_ref.env.mcp_mode=stdio\
    actor_rollout_ref.env.tool_manager=qwen2_5_vl\
    actor_rollout_ref.env.enable_thinking=False\
    actor_rollout_ref.env.config_path=envs/configs/mcp_tools1.pydata\
    actor_rollout_ref.env.use_process_reward=False\
    reward_rollout.if_use_reward_rollout=False\
    reward_rollout.rollout.tensor_model_parallel_size=2\
    reward_rollout.rollout.model_name=$REWARD_MODEL_PATH\
    reward_rollout.rollout.response_length=1024\
    reward_model.reward_manager=parallel\
    algorithm.kl_ctrl.kl_coef=0.001\
    trainer.critic_warmup=0\
    trainer.logger=['wandb']\
    trainer.project_name='GRPO_Visual'\
    trainer.experiment_name='Visual'\
    trainer.n_gpus_per_node=8\
    trainer.nnodes=1\
    trainer.val_before_train=False\
    trainer.default_local_dir=ckpt\
    trainer.default_hdfs_dir=null\
    trainer.save_freq=20\
    trainer.test_freq=10\
    trainer.total_epochs=5 $@ 2>&1 | tee grpo.log
